name: Deploy Laravel Docker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "production"
        type: string

jobs:
  deploy:
    name: Deploy Laravel on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa e${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
        cd /var/www/html/FSD
        git pull origin main
        cd FSD-Laravel
        cp .env.example .env
        sed -i "s/APP_KEY=.*/APP_KEY=${{ secrets.APP_KEY }}/" .env
        sed -i "s/APP_URL=.*/APP_URL=${{ secrets.APP_URL }}/" .env
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env
        cd ..
        docker-compose down
        docker-compose build
        docker-compose up -d
        docker exec laravel-app php artisan migrate --force
        docker exec laravel-app php artisan key:generate
        docker exec laravel-app php artisan config:clear
        docker exec laravel-app php artisan cache:clear
        docker exec laravel-app php artisan route:clear
        docker exec laravel-app chown -R www-data:www-data /var/www/html/storage
        docker exec laravel-app chmod -R 775 /var/www/html/storage
        EOF